name: Build Bootloader OS

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NASM
        run: sudo apt update && sudo apt install -y nasm

      - name: Build boot.img
        run: make

      - name: Upload boot image
        uses: actions/upload-artifact@v4
        with:
          name: boot-img
          path: boot.img
