name: Build My OS

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential grub-pc-bin xorriso nasm mtools

      - name: Build ISO
        run: make iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: myos.iso
          path: myos.iso
